### ISSUE TITLE
Compiling string concat is very slow

### ISSUE THREAD

**Issue by dcurrie** [koka-lang/koka#138]
I thought I found a compiler non-termination bug, but when constructing a minimal test case I found that it was just taking a **very** long time to complete. I stopped minimizing here, file name `catest.kk`:
```koka
fun show-a-few-ints(): string {
  val x = 42
  val y = -1
  1.show + " " + 2.show + " " + 3.show
    + " " + 4.show + " " + 5.show
    + " " + x.show + " " + y.show
}
public fun main() {
  println("A few numbers: " + show-a-few-ints())
}
```
on macOS 10.15.7 Core i9:
```
e% time koka -c ./catest.kk      
compile: catest.kk
loading: std/core
loading: std/core/types
loading: std/core/hnd
check  : catest
linking: catest
created: out/v2.0.14/clang-debug/catest
koka -c ./catest.kk  44.13s user 6.51s system 99% cpu 50.720 total
```
Almost a minute for a 10 line file. If I remove just one item it drops to under 3 seconds. Here's the change:
```koka
  1.show + " " + 2.show // + " " + 3.show
```

**Comment by SchrodingerZhu** [comment]
@dcurrie. I guess the problem is not only for string
```
fun show-a-few-ints(): string {
  val x = 42
  val y = -1 
  val z = 1
  (x + y + z    
    + 1 + 2 + 3
        + x + y + z
            + 1 + 2 + 3).show
}
public fun main() {
  println("A few numbers: " + show-a-few-ints())
}
```

This also takes a while to finish

**Comment by daanx** [comment]
Ah -- yes; this is not great; @dcurrie , this is related to the overloading question you had earlier: currently, Koka uses static overloading but that does not always work well with inference and in some cases, like on (+), it becomes quadratic in the expression which is what we see here. The plan is to implement "real" ad-hoc overloading though using the "second look at overloading" approach (instead of type classes) and that will fix this issue; already Koka supports qualified types internally so it should be a manageable amount of work.  However, not sure when this feature lands -- I hope within the next 2 months but it is a busy time and there are many things to be done :-)

**Comment by daanx** [comment]
Just to add: sometimes you can avoid this behaviour by giving more type information, like on the addition, specify it becomes an `: int` or a `: string`.

**Comment by TimWhiting** [comment]
These examples no longer take a long time to infer types / compile. Thanks for the feedback!
