### ISSUE TITLE
Should allow for type-based dispatch on values and return type

### ISSUE THREAD

**Issue by Pauan** [koka-lang/koka#15]
Right now, it's possible to have multiple functions with the same name, as long as their input types differ:

```koka
fun foo(a: int): int { a }
fun foo(a: string): string { a }

fun main() {
  println(foo(1))
  println(foo("1"))
}
```

However, it's not possible to have functions that differ only in their *return* types:

```koka
fun foo(): int { 1 }
fun foo(): string { "1" }

fun main() {
  println(foo())
  println(foo())
}
```

It's also not possible to have *values* that differ in their types:

```koka
val foo: int = 1
val foo: string = "1"

fun main() {
  println(foo: int)
  println(foo: string)
}
```

This limitation prevents a lot of useful stuff: `empty: a`, `parse: string -> a`, `from-list: list<a> -> b<a>` etc.

**Comment by TimWhiting** [comment]
This is now possible. All names must be qualified so that they can be referred to unambiguously though, but type inference will do it's best to find the right function.

See the new samples for more information, and open new issues or a discussion topic for feedback! https://github.com/koka-lang/koka/blob/dev/samples/syntax/qualifiers.kk and https://github.com/koka-lang/koka/blob/dev/samples/syntax/implicits.kk
