### ISSUE TITLE
Unable to extend a function with an effect

### ISSUE THREAD

**Issue by faiface** [koka-lang/koka#164]
Hello :) I just started exploring Koka and I hit this. I tried to find a minimal example. If I write this:

```koka
fun test() : console int {
    42
}
```

everything is alright. However, if I try something like this:

```koka
fun test(f : () -> e a) : <console|e> a {
    f()
}
```

the type-checking fails with:

```
test.kk(34,41): error: effects do not match
  context        : fun test(f : () -> e a) : <console|e> a {
                       f()
                   }
  term           :                                         {
                       f()
                   }
  inferred effect: $e
  expected effect: <console|$e>
```

Am I missing something or is this a bug?

**Comment by anfelor** [comment]
Hi, thanks for getting in touch!

The idea is that Koka will unify the effects of `f` and the surrounding context. That means it will try to instantiate `e` such that `e` and `console|e` are equal. But this can't be done of course!

Koka does that because of its implementation of effect handlers: You can have multiple nested handlers for an effect, but only the last one will be used. But your implementation of `test` would imply that `f` will take the second to last console effect handler (since the last one is the `console` handler that you added to `e`) and Koka does not support this.

You can write your example as
```
fun test(f : () -> <console|e> a) : <console|e> a {
    f()
}
```
Here it is clear that `f` will use the same console effect handler as the surrounding context. You can still pass a function to `test` that doesn't use the `console` effect, since effects can always be added even if not needed.

**Comment by faiface** [comment]
Thanks for a very clear explanation!

If I may, I would offer an opinion, though, that this seems to me like a limitation for the purpose of simplifying the implementation. I feel like making it so that "the last handler which supports the effect will be used" would be more flexible. But maybe there are some fundamental problems with that, if so, I'd love to know.

**Comment by anfelor** [comment]
Koka will always use the last handler that supports an effect and not simply the last handler of some effect :)

You can still ask Koka to "skip" one effect handler by using masking:
```
fun test(f : () -> e a) : <console|e> a {
    mask<console>(f)
}
```

**Comment by faiface** [comment]
Oh! Okay, I didn't know about this `mask` thing, that pretty much solves it. Thanks a lot!

**Comment by anfelor** [comment]
Glad to help! It is described in more detail at: https://koka-lang.github.io/koka/doc/book.html#sec-mask
