### ISSUE TITLE
How can I use gcc as koka's C++ compiler (Windows)

### ISSUE THREAD

**Issue by starskyC** [koka-lang/koka#176]
I wish to run koka in git bash, however it seems like it only runs in x64 Native Tool Command Prompt.
In git bash, it always show "Invalid Arguments". I'm curious why but couldn't figure it out.
In Native Tool cmd, I tried `koka --cc=gcc` and a bunch of error went out.

**Comment by daanx** [comment]
Hi @starskyC -- on Windows it is easiest to install the clang compiler (here is the [installer](https://prereleases.llvm.org/win-snapshots/LLVM-12.0.0-6923b0a7-win64.exe)) as you C compiler. Koka will use it automatically even if you are within a git bash prompt.  

Let me know if this works for you

ps. more explanation: on Windows there are 3 options for C compilers:
* `clang-cl`: works easiest; install with the above link. This is preferred by Koka.
* `cl`: the Microsoft Visual C compiler. This works as well but needs to be run inside an x64 Native Tools prompt or otherwise the compiler cannot link with the system libraries. I do not think this can work from inside a git bash.
* `mingw`: the gcc compiler on Windows; this is not generally easy to install but it comes with ghc and can be used when using `stack exec`.
* Also, `git bash` as a non-standard environment of course, in my experience it works best to use a simple Windows `cmd` prompt or  use WSL2 (with Ubuntu 20.04) to have a full Linux environment.

**Comment by starskyC** [comment]
@daanx Thank you for helping me. I tried uninstall everything and reinstall them in their default location. (llvm, koka etc)
However, when I run `koka` either in cmd or git bash, they both give out
`invalid argument` and it couldn't enter the interactive mdoe.
I'm curious what kind of error will cause this output.

**Comment by starskyC** [comment]
Anyway, it seems like to work in x64 Native Tools Command Prompt. Thankyou for your time! 😃 All I want is to do some experiment with the effect stuff and anything that works is enough.

**Comment by daanx** [comment]
Great you got it working! However, it is strange it didn't work in the `cmd` -- I worked hard on the installer so it would be great if you could give more details -- I wonder if I have something in my PATH that is missing on your system. 

- can you send the error output you get?
- does it happen when trying to run koka?  
- can you try `koka -v2` to see perhaps more verbose messages

Thanks

**Comment by starskyC** [comment]
Hi @daanx . Sorry for the late reply. 
I've got
`C:\Program Files\LLVM\bin`
`C:\Users\Administrator\AppData\Roaming\local\bin`
and of course others but aren't related to koka by any mean, at least I think.

I've also got the `koka_editor code --goto %f:%l:%c` and `koka_version v2.1.6` in the environmental variables.

When I try to run `koka` or `koka -c ./test.kk -o .` in cmd, they both give out `invalid argument`. i.e. both Interactive mode and Compile mode don't work. I also tried using -v2 option yet the output stays the same. My guess is that things went wrong when koka tries to do something related to linking because I remember this error output when I have to deal with linking in another project. 

Can you please provide me what argument(s) are passed to the linker, and what linker command does the koka run? Maybe I can work this way and make it run in cmd.

Thanks
