### ISSUE TITLE
REPL breaks when printing lists

### ISSUE THREAD

**Issue by Pauan** [koka-lang/koka#23]
When I enter `[]` into the REPL, I get this error:

```
(1, 0): error: the type of 'main' must be a function without arguments
  expected type: () -> io ()
  inferred type: forall<a> () -> list<a>
```

When I enter `[[1]]` into the REPL, I get this error:

```
(1, 0): error: no 'show' function defined for values of type: list<list<int>>
```

This is somewhat related to #20. It can be solved by having the REPL automatically pretty-print all built-in types.

It would also be nice if it were possible to create pretty printers for custom types, but that will probably require some sort of typeclass mechanism (#16)

**Comment by anfelor** [comment]
The current behaviour is quite similar to what is reported in this issue:
```
> []
check  : interactive
(1, 0): error: no 'show' function defined for values of type: list<12>

> [1]
check  : interactive
check  : interactive
linking: interactive
created: out/v2.1.7/gcc-debug/interactive
 
[1]

> [[1]]
check  : interactive
(1, 0): error: no 'show' function defined for values of type: list<list<int>>
```
As you mentioned, this is related to a lack of typeclass mechanism. There are plans for overloading based on 'A second look at Overloading', which will resolve this issue.

I will be closing this issue, since it is not really related to the REPL and will be fixed by an overloading system which we already track at, e.g. #138
