### ISSUE TITLE
Polymorphic effect cannot have seperate handlers

### ISSUE THREAD

**Issue by locriacyber** [koka-lang/koka#241]
The following code should work in theory, since `raise_baby` is polymorphic. But currently, koka only accepts the one handler for polymorphic effects.

```
struct duck
struct swain

effect raise_baby<a, b>
    fun raise_baby(aaa: a, bbb: b): ()

fun main()
    with handler fun raise_baby(a: duck, b: duck)
        println("lead to water")
    with handler fun raise_baby(a: duck, b: swain)
        println("ignore")
    with handler fun raise_baby(a: swain, b: swain) // only this one is inferred
        println("put on back")
    val a = Duck()
    val c = Swain()
    raise_baby(a, a)
    raise_baby(a, c)
    raise_baby(c, c)
```

**Comment by locriacyber** [comment]
The example was from https://www.oxinabox.net/2020/02/09/whycompositionaljulia.html

**Comment by locriacyber** [comment]
I'm trying to have type classes that only work in a scope. `raise_baby<duck,duck>` is a different effect than `raise_baby<duck,swan>`, so I think they should have different handlers.

**Comment by rubikscraft** [comment]
@locriacyber Hi, the github [discussions](https://github.com/koka-lang/koka/discussions) tab is probably a better place for this question. 

Right now koka has a gitter chatroom, and since some time this is compatible with matrix. It is pretty inactive, but you can join it [here](https://matrix.to/#/#koka-lang_koka:gitter.im).

**Comment by rubikscraft** [comment]
Hi @locriacyber, polymorphic effects not working this way is an intended part of koka. It would be extremely difficult and slow to add this. Because polymorphic effects would require the type of the arguments to be known at runtime. This means runtime types would also need to be added, and that only slows things down and makes them more complicated.

**Comment by locriacyber** [comment]
I don't think runtime types are needed. Each `val` binding has **one** type, and the effects in the above example are all compile-time known.

**Comment by locriacyber** [comment]
I don't think runtime types are needed. Each `val` binding has **one** type, and the effects in the above example are all compile-time known.

**Comment by rubikscraft** [comment]
Yes, in this example it is indeed clear what side effect handler should be called. But these handlers could be completely unkown and/or different for the same function. And in that case you need the runtime type to call the correct function.

**Comment by locriacyber** [comment]
> But these handlers could be completely unkown and/or different for the same function.

Can you give an example?

**Comment by daanx** [comment]
The restriction is indeed fundamental (and intended). The reasons are three-fold: 

- First of all, we want Koka to have an "untyped dynamic semantics", that is, we can erase all types and still run the program (and it will be not `wrong` for a well-typed program). (Note, this is unlike Haskell for example where we cannot interpret `show (read "")` without knowing the intermediate result type of `read`)

- Secondly, we adhere strictly to the algebraic effect handler semantics as outlined for example in [1]. This gives us a firm basis in theory and has known good properties with respect to composition of effect handlers for example (unlike `call/cc` for example, or arbitrary monads). 

- Thirdly, we want to have principal type inference where any well-typed program can be assigned automatically a most general type (i.e. the best type). To make this work, we need deterministic "row unification" where the effect rows can be unified in a principal way (so, type rules have only equality between types (easy) and never _in-equalities_ between types (very hard; a common case are subtypes leading to co- and contra-variance etc).)

The third one means that when we have an effect row with different effects "labels", like `<exn,div>` we can treat this as equal to `<div,exn>` when doing type inference. It also means that we cannot have  polymorphic _labels_, like `<a,b>` or otherwise we cannot decide the equivalence `<div,exn> ~= <a,b>` for example deterministically. (note: we can have polymorphic _rows_, like `<div,exn | e>` where `e` is polymorph as that is decidable [2]). 

Moreover, we can have (polymorpic) type parameters to effect "labels", like `<foo<int>,foo<bool>` but these cannot be reordered, and `<foo<int>, foo<bool>  != <foo<bool>, foo<int>>`.  At runtime this means that the first one needs an outer f
`foo<bool>` handler, while the inner handler should be `foo<int>` and the other way around for the second one. The reason is that at runtime there is only the "foo" effect tag and the innermost handler always handles the effect (which is what gives us an untyped dynamic semantics).  If you want to address another handler you need to use `mask` to skip the innermost handler.

Hope this helps :-)  The references may contain more examples. Here is a short example that shows that we cannot be rely on type parameters to infer which handler should be invoked (as in your original example):

```
effect foo<a>
  fun foo( xs : list<a> ) : int

fun main()
  with fun foo( xs : list<int> ) 
    xs.sum
  with fun foo( xs )
    xs.length
  with fun foo( xs : list<bool> )
    if xs.all(id) then 1 else 0

  <expr>
```
Here we set up three handlers, so the inferred effect context for `<expr>` is `< foo<bool>, foo<a>, foo<int> >` -- in that order! So, if I write `foo([True])` for `<expr>` it will be handler by the inner handler (and return 1).   If I write `foo([1,2])` I will get a type error as the effect of `foo([1,2]) : <foo<int> | e>` does not unify with `< foo<bool> | <foo<a>, foo<int>> >`. If I want to really use the outer hander, I need to write `mask<foo>{ mask<foo>{ foo([1,2]) } }` -- ouch :-).   

You may argue that we could infer this automatically in this case, but consider writing `foo([])` ... now any of the handlers can potentially match and there is no "best" choice. This is especially trouble some for type inference: what if I have an argument `xs` and see `xs.length` and infer it has type `list<a>` and then I see `foo(xs)` and make some choice, say the bool handler, but then later we see `if True then xs else [1,2]` and now it would have been better to have chosen the `int` handler earlier on. This is why determinism is important for type inference.


[1] Ningning Xie and Daan Leijen. &ldquo; Generalized Evidence Passing for Effect Handlers&rdquo; In The 26th ACM SIGPLAN International Conference on Functional Programming (ICFP), August 2021.
Also as MSR-TR-2021-5, Mar, 2021. 
[pdf](https://www.microsoft.com/en-us/research/publication/generalized-evidence-passing-for-effect-handlers/)

[2] Daan Leijen, "Extensible records with scoped labels" [pdf](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/scopedlabels.pdf)

**Comment by locriacyber** [comment]
What's the use case for this type of effect handler?
```
  with fun foo( xs )
    xs.length
```

If we disallow "forall a: foo<a>" handler, we can use `foo<bool>` as tag, not just `foo`, right?

**Comment by locriacyber** [comment]
@daanx can you move this issue to Github discussion?
