### ISSUE TITLE
Installation on Termux

### ISSUE THREAD

**Issue by xigoi** [koka-lang/koka#242]
This is probably more of a Termux issue than a Koka issue, but I'm putting it here in case someone knows the solution.

I'd like to install Koka in [Termux](https://termux.com/) so I can play around with it on my phone. The build script worked after I did the following modifications:

- Line 9: `PREFIX="/data/data/com.termux/files/usr/"`
- Line 281: `ninja-build` -> `ninja`

However, I can't execute the produced executable. It's giving the "No such file or directory" error.

**Comment by rubikscraft** [comment]
Hi, cool that you got it to even build. May I ask what build system you used? (stack, cabal or minbuild). And could you post the complete error output of the produced executable?

**Comment by xigoi** [comment]
I used the `install.sh` script. Unfortunately, I didn't manage to install Stack, so I can't build from source.

```
❯ koka
bash: /data/data/com.termux/files/usr/bin/koka: No such file or directory

❯ readelf -l /data/data/com.termux/files/usr/bin/koka | grep interpreter
      [Requesting program interpreter: /lib/ld-linux-aarch64.so.1]
```

**Comment by rubikscraft** [comment]
I looks like it cant find find the program interpreter, as android doesn't store its ld in /lib. 
Maybe there is a way to redirect this location, but im pretty sure it wil only hit more problems after that.

You could otherwise try building koka from scratch using the ./util/minbuild.sh script, as ghc is available for termux. You could even try and build cabal inside termux and use that build koka.
