### ISSUE TITLE
Syntax error when returning anonymous lambda

### ISSUE THREAD

**Issue by Pauan** [koka-lang/koka#44]
Reproducible code in the REPL:

```
> fun foo() { fun() {} }
              ^
((1),13): error: invalid syntax
 unexpected keyword fun.anon
 expecting ";", "fun", "function", "val", "var", expression, "return" or "}"
```

It's possible to workaround this issue by wrapping the lambda in parens:

```
> fun foo() { (fun() {}) }
```

**Comment by b-studios** [comment]
It appears this is purposfully so, since `nofunexpr` is only used as part of [statements](https://github.com/koka-lang/koka/blob/c6cb3d621ffabe623e9ffc32d83a33e6038c4484/src/Syntax/Parse.hs#L1048). I guess this is to avoid ambiguity of the `fun` keyword in statements and guarantee 1-token-lookahead. But I agree with @Pauan that this is unexpected.

**Comment by dhil** [comment]
This is the expected behaviour. In a binding context the `fun` keyword begins a named function definition, whilst in an expression context it begins an unnamed function definition (aka. a lambda expression).

According to the [specification of Koka](https://koka-lang.github.io/koka/doc/kokaspec.html#sec-full-grammar-specification), the body of a function definition is both a binding context and a restricted expression context, which crucially do not admit lambda expressions. Thus the syntax error arises because the term is an ill-formed named function definition. As you observed, the correct way to return a unnamed function is to wrap it in parentheses, which delimits a full expression context.

An argument could be made for relaxing the restriction of expression contexts in function bodies.
