### ISSUE TITLE
segfault in vector-init

### ISSUE THREAD

**Issue by chtenb** [koka-lang/koka#443]
*Reproduction*
```koka
pub fun vector/append(first : vector<a>, second : vector<a>) : _ vector<a>
  vector-init(first.length + second.length, fn(i) index-two(first, second, i))
  
fun vector/index-two(first : vector<a>, second : vector<a>, i: int) : _ a
  if i < first.length then first[i] else second[i]

pub fun main()
  val x = [1,2,3].vector
  val y = x.append(x)
  ()
```

**Comment by TimWhiting** [comment]
Don't you want `second[i - first.length]`?

**Comment by chtenb** [comment]
Yes that's right, but it should not segfault I think? It should throw the appropriate exception and error message in the console.

**Comment by TimWhiting** [comment]
Yeah, that should have been fixed in this commit: https://github.com/koka-lang/koka/commit/03793a957ee98b542f4ed4a5aefd1ae172f4506e

**Comment by TimWhiting** [comment]
Ahh, I know the issue. Throwing inside of initializing a vector causes the partially initialized vector to be freed, but not all of it's elements exist yet, so it tries to free invalid memory.

**Comment by chtenb** [comment]
Are `int`s inside a vector refcounted individually?

**Comment by TimWhiting** [comment]
Yes, vectors are not currently specialized to non-refcounted types (as far as I know), and even if they were `int`s are arbitrary precision integers which use an efficient pointer tagged representation until they overflow: [paper on integers in koka](https://www.microsoft.com/en-us/research/publication/what-about-the-integer-numbers-fast-arithmetic-with-tagged-integers-a-plea-for-hardware-support/). Since they can overflow they do need ref-counting. `int32` or `int64` in contrast are non-refcounted primitive machine types.

**Comment by daanx** [comment]
Thanks!  Tim was right, the vector was half initialized and freeing would fail. I fixed it in the latest `dev` by always initializing such array first with dummy values; since the vector is not reachable during initialization this should be safe.
