### ISSUE TITLE
Need help writing generator using named handlers

### ISSUE THREAD

**Issue by hflsmax** [koka-lang/koka#574]
Hi, I'm implementing a generator using named handler. The original Koka program is at https://github.com/effect-handlers/effect-handlers-bench/blob/main/benchmarks/koka/generator/main.kk

I'm having difficulty making the program type check. I think the issue is that the Thunk carries the named handler and makes it escape the scope. The typing error is not very helpful and I would like to get some help.

The program I have is below
```
module main

import std/os/env

named effect yield
  ctl yield(x : int) : ()

type tree
  Leaf
  Node(left : tree, value : int, right : tree)

type generator
  Empty
  Thunk(value : int, next: () -> div generator)

fun make(n : int) : div tree
  if n == 0 then
    Leaf
  else
    val t = make(n - 1)
    Node(t, n, t)

fun iterate(t : tree, r: hnd/ev<yield>): <pure> ()
  match t
    Leaf -> ()
    Node(left, v, right) ->
      iterate(left, r)
      r.yield(v)
      iterate(right, r)

fun generate(f: (hnd/ev<yield>) -> <pure> ()): <pure> generator
  with r <- named handler
    return(_) Empty
    ctl yield(x)
      Thunk(x, fn() { resume(())})
  f(r)

fun sum(a : int, g : generator) 
  match g
    Empty -> a
    Thunk(v, f) -> sum(v + a, f())

fun run(n : int): <pure> int
  val f: (hnd/ev<yield>) -> <pure> () = fn(r: hnd/ev<yield>) { iterate(make(n), r)}
  sum(0, generate(f))

pub fun main()
  val n = get-args().head("").parse-int().default(5)
  val r = run(n)
  println(r)
```

**Comment by TimWhiting** [comment]
```
type generator
  Empty
  Thunk(value : int, next: () -> pure generator)
```

I agree the type error is not very clear here. 

The named handler creates a generator where thunk's second field has the type `fn() -> pure generator` since that is what generator's type definition is. However, your `f` is run under the handler and can raise an exception (`pure`), so when resuming the thunk there is a potential for an exception. Therefore the function type in the generator datastructure is the problem. The simple fix is to change the next field's type.

The more complicate fix is to make the generator datatype abstract over additional effects:

```
import std/os/env

named effect yield
  ctl yield(x : int) : ()

type tree
  Leaf
  Node(left : tree, value : int, right : tree)

type generator<e>
  Empty
  Thunk(value : int, next: () -> <div|e> generator<e>)

fun make(n : int) : div tree
  if n == 0 then
    Leaf
  else
    val t = make(n - 1)
    Node(t, n, t)

fun iterate(t : tree, r: hnd/ev<yield>): pure ()
  match t
    Leaf -> ()
    Node(left, v, right) ->
      iterate(left, r)
      r.yield(v)
      iterate(right, r)

fun generate(f: (hnd/ev<yield>) -> <div|e> ()): <div|e> generator<e>
  with r <- named handler
    return(_) Empty
    ctl yield(x)
      Thunk(x, fn() { resume(())})
  f(r)

fun sum(a : int, g : generator<e>): <div|e> int
  match g
    Empty -> a
    Thunk(v, f) -> sum(v + a, f())

fun run(n : int): pure int
  val f: (hnd/ev<yield>) -> pure () = fn(r: hnd/ev<yield>) { iterate(make(n), r)}
  sum(0, generate(f))

pub fun main()
  val n = get-args().head("").parse-int().default(5)
  val r = run(n)
  println(r)
```

For future consideration please use the github discussions for questions instead of issues, and feel free to join the unofficial community on Discord [invite link](https://discord.com/invite/CEkHHnTqEv).

**Comment by hflsmax** [comment]
Amazing! Thanks for your help! I'll post to the other places next time.
