### ISSUE TITLE
Cracking Caesar encoding is missing float64 import

### ISSUE THREAD

**Issue by Ugzuzg** [koka-lang/koka#578]
https://koka-lang.github.io/koka/doc/book.html#sec-a-larger-example--cracking-caesar-encoding

I was following along with the Caesar encoding example, but wasn't able to compile it. Turned out, float64 got [moved out of core](https://github.com/koka-lang/koka/commit/73fd741170c7e6ed319620bfaef8b607d5cd7c62).

**Comment by zephyrtronium** [comment]
samples/basic/caesar.kk mentioned at the bottom of the section is up to date. It contains other definitions missing from the book, not only the std/num/float64 import. Otherwise there are only a few minor differences: `fun example-uncaesar` instead of `fun test-uncaesar` and `fun chisqr` using `.sum` instead of `.foldr(0.0,(+))`.

Particularly given the lack of a module declaration in the book, I interpret it as saying, "Here are the interesting parts of an example; the full source code is in this file," rather than "Here is a full runnable example." If there's anything to fix here, I would argue it's the type checker error message you get in `fun percent` without the import: the error is on the `100.0` saying it expected an int, but the real problem is that it can't resolve `int/float64`.

**Comment by Ugzuzg** [comment]
samples/basic/caesar.kk comes after the code snippet and is separated by an additional paragraph, which makes it hard to notice. The instruction only tells you how to load it into the interactive environment. It's not clear from the book where to look for the source itself. 

If the import shouldn't be added, then I would, for transparency's sake, mention that the snippet only contains the interesting bits and add a link to full source before the snippet.
