### ISSUE TITLE
Koka tutorial has non-divergent effect type signature for `looptest`

### ISSUE THREAD

**Issue by rauchg** [koka-lang/koka#6]
![image](https://cloud.githubusercontent.com/assets/13041/24087593/19cfde50-0cde-11e7-9524-209c1e8ea40c.png)

When I hover the `looptest` identifier, I don't see `div`, which is to be expected from the usage of `while`? I also don't see `exn`, which should come from `error`.

**Comment by daanx** [comment]
Hi :-) Thanks for trying Koka! The `pure` effect is an alias for `<exn,div>` and includes both exceptions and possible divergence. The `total` effect is used for mathematically total functions. The terminology is chosen because it corresponds to Haskell's notion of purity where "pure" functions (and values!) can actually diverge or raise exceptions.

**Comment by daanx** [comment]
btw. You can see the definition of `pure` in the [`std/core`](https://koka-lang.github.io/koka/doc/std_core.html#type_space_pure) library.

**Comment by rauchg** [comment]
@daanx that makes it super clear. Thank you
