### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by atennapel** [koka-lang/koka#61]
- The type system of Koka in the papers on it seem to be similar to Hindley-Milner, but I also saw a ST type effect which means higher-ranked polymorphism is needed. Is the implemented type system based on a specific paper?
- Does Koka support indexed monad style effects? Like an indexed state monad, where the set operation can change the type of the state.
- Can Koka emulate ML-style references (dynamically allocated references)? Similar to how Eff can, using resources.

**Comment by Pauan** [comment]
> Can Koka emulate ML-style references (dynamically allocated references)? Similar to how Eff can, using resources.

Koka already has ML-style references:

```koka
fun fib(n) 
{
  val x = ref(0)
  val y = ref(1)
  repeat(n) {
    val y0 = !y
    y := !x + !y
    x := y0
  }
  return !x
}
```

Or you can use `var` instead, which is just syntax sugar for `ref`:

```koka
fun fib(n) 
{
  var x := 0
  var y := 1
  repeat(n) {
    val y0 = y
    y := x+y
    x := y0
  }
  return x
}
```

I can't really answer your other two questions.

**Comment by atennapel** [comment]
From what I can understand from the papers on Koka, the references are basically exactly the same as the ST monad in Haskell, but runST is inserted automatically where it can. Is this correct? Does this also mean that, just like Haskell, the references can not be defined in Koka itself, using algebraic effects for example.

**Comment by dhil** [comment]
> Does this also mean that, just like Haskell, the references can not be defined in Koka itself, using algebraic effects for example.

To the best of my knowledge Koka **does not** have support for generative effects, meaning that references are not definable.

**Comment by atennapel** [comment]
Do you by any chance know some papers about dynamic or generative effects? I've only found it mentioned in the Eff paper, where references are done using resources, but this part is left out of the formalization and type systems.

**Comment by dhil** [comment]
> The type system of Koka in the papers on it seem to be similar to Hindley-Milner, but I also saw a ST type effect which means higher-ranked polymorphism is needed. Is the implemented type system based on a specific paper?

Several relevant papers form the basis for Koka: [Extensible records with scoped labels](http://www.cs.ioc.ee/tfp-icfp-gpce05/tfp-proc/21num.pdf), [Koka: Programming with Row Polymorphic Effect Types](https://arxiv.org/abs/1406.2061v1), and [Type Directed Compilation of Row-Typed Algebraic Effects](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/12/algeff.pdf) to name a few.

> Does Koka support indexed monad style effects? Like an indexed state monad, where the set operation can change the type of the state.

To the best of my knowledge, no.

> Do you by any chance know some papers about dynamic or generative effects? I've only found it mentioned in the Eff paper, where references are done using resources, but this part is left out of the formalization and type systems. It's mentioned in the Koka and Frank papers, but only in a few sentences.

I am not familiar with other literature on the subject than [Programming with Algebraic Effects and Handlers](http://math.andrej.com/wp-content/uploads/2012/03/eff.pdf) and [An Effect System for Algebraic Effects and Handlers](https://arxiv.org/pdf/1306.6316.pdf). 

You may find it informative to consult the [collaborative effects bibliography](https://github.com/yallop/effects-bibliography) for related literature.

I hope this at least provides some answers to your questions or pointers for further information. Otherwise feel free to reopen the issue.
